---
title: "Publication Ready"
author: "Amalan"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,fig.width = 15,fig.height = 20,message = FALSE,warning = FALSE)
library(here)
library(ggplot2)
library(dplyr)
library(tidyr)
library(LaplacesDemon)
library(xtable)
library(flextable)
library(grid)
library(cowplot)
library(linguisticsdown)
library(ggpubr)
```

# Using Normal Distribution for Data

## Model : `r params$Model_Path` 

```{r load Identical Data}
Old_Labels<-c("Real Model",paste0("Assumed Model ",1:3))
New_Labels<-c("RM",paste0("AM ",1:3))

# Random Sampling
load(here("Non_Identical_r0","Summary","Classical",params$Model_Path,"Data","Efficiency",
          "No_Correlated_Covariate_RS.RData"))

for (i in 1:length(Old_Labels)) 
{
  All_Bias$Model[All_Bias$Model==Old_Labels[i]] <-paste0("RS ",New_Labels[i])
  All_EMSE$Model[All_EMSE$Model==Old_Labels[i]] <-paste0("RS ",New_Labels[i])
  All_Info$Model[All_Info$Model==Old_Labels[i]] <-paste0("RS ",New_Labels[i])
  All_MSE$Model[All_MSE$Model==Old_Labels[i]] <-paste0("RS ",New_Labels[i])
  All_VAR$Model[All_VAR$Model==Old_Labels[i]] <-paste0("RS ",New_Labels[i])
  Accuracy_Data$Model[Accuracy_Data$Model==Old_Labels[i]] <-paste0("RS ",New_Labels[i])
}

RS_Bias<-All_Bias 
RS_EMSE<-All_EMSE
RS_Info<-All_Info
RS_MSE<-All_MSE
RS_VAR<-All_VAR
RS_ACC<-Accuracy_Data

remove(All_Bias,All_EMSE,All_MSE,All_Info,All_VAR,Accuracy_Data)

# OSMAC
load(here("Identical_r0","Summary","Classical",params$Model_Path,"Data","Efficiency",
          "No_Correlated_Covariate_OSMAC.RData"))
remove_stuff<-c(paste0("Assumed New ",1:3))

All_Bias<-All_Bias[!(All_Bias$Model %in% remove_stuff),]
All_EMSE<-All_EMSE[!(All_EMSE$Model %in% remove_stuff),]
All_MSE<-All_MSE[!(All_MSE$Model %in% remove_stuff),]
All_Info<-All_Info[!(All_Info$Model %in% remove_stuff),]
All_VAR<-All_VAR[!(All_VAR$Model %in% remove_stuff),]
Accuracy_Data<-Accuracy_Data[!(Accuracy_Data$Model %in% remove_stuff),]

Old_Labels<-c("Real",paste0("Assumed Old ",1:3),"Model Free")
New_Labels<-c("RM",paste0("AM ",1:3),"MF")


## mMSE
for (i in 1:length(Old_Labels)) 
{
  All_Bias$Model[All_Bias$Model==Old_Labels[i] & All_Bias$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
  All_EMSE$Model[All_EMSE$Model==Old_Labels[i] & All_Bias$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
  All_Info$Model[All_Info$Model==Old_Labels[i] & All_Bias$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
  All_MSE$Model[All_MSE$Model==Old_Labels[i] & All_Bias$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
  All_VAR$Model[All_VAR$Model==Old_Labels[i] & All_Bias$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
  Accuracy_Data$Model[Accuracy_Data$Model==Old_Labels[i] & All_Bias$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
}

## mVc
for (i in 1:length(Old_Labels)) 
{
  All_Bias$Model[All_Bias$Model==Old_Labels[i] & All_Bias$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
  All_EMSE$Model[All_EMSE$Model==Old_Labels[i] & All_Bias$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
  All_Info$Model[All_Info$Model==Old_Labels[i] & All_Bias$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
  All_MSE$Model[All_MSE$Model==Old_Labels[i] & All_Bias$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
  All_VAR$Model[All_VAR$Model==Old_Labels[i] & All_Bias$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
  Accuracy_Data$Model[Accuracy_Data$Model==Old_Labels[i] & All_Bias$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
}

OSMAC_mMSE_Bias<-All_Bias[All_Bias$Type == "mMSE",] 
OSMAC_mMSE_EMSE<-All_EMSE[All_EMSE$Type == "mMSE",]
OSMAC_mMSE_Info<-All_Info[All_Info$Type == "mMSE",]
OSMAC_mMSE_MSE<-All_MSE[All_MSE$Type == "mMSE",]
OSMAC_mMSE_VAR<-All_VAR[All_VAR$Type == "mMSE",]
OSMAC_mMSE_ACC<-Accuracy_Data[Accuracy_Data$Type == "mMSE",]

OSMAC_mVc_Bias<-All_Bias[All_Bias$Type == "mVc",] 
OSMAC_mVc_EMSE<-All_EMSE[All_EMSE$Type == "mVc",]
OSMAC_mVc_Info<-All_Info[All_Info$Type == "mVc",]
OSMAC_mVc_MSE<-All_MSE[All_MSE$Type == "mVc",]
OSMAC_mVc_VAR<-All_VAR[All_VAR$Type == "mVc",]
OSMAC_mVc_ACC<-Accuracy_Data[Accuracy_Data$Type == "mVc",]

remove(All_Bias,All_EMSE,All_MSE,All_Info,All_VAR,Accuracy_Data)

# All elements
All_Bias<-rbind(RS_Bias,
                OSMAC_mMSE_Bias[,!(colnames(OSMAC_mMSE_Bias) %in% "Type")],
                OSMAC_mVc_Bias[,!(colnames(OSMAC_mVc_Bias) %in% "Type")])
All_EMSE<-rbind(RS_EMSE,
                OSMAC_mMSE_EMSE[,!(colnames(OSMAC_mMSE_EMSE) %in% "Type")],
                OSMAC_mVc_EMSE[,!(colnames(OSMAC_mVc_EMSE) %in% "Type")])
All_MSE<-rbind(RS_MSE,
                OSMAC_mMSE_MSE[,!(colnames(OSMAC_mMSE_MSE) %in% "Type")],
                OSMAC_mVc_MSE[,!(colnames(OSMAC_mVc_MSE) %in% "Type")])
All_Info<-rbind(RS_Info,
                OSMAC_mMSE_Info[,!(colnames(OSMAC_mMSE_Info) %in% "Type")],
                OSMAC_mVc_Info[,!(colnames(OSMAC_mVc_Info) %in% "Type")])
All_VAR<-rbind(RS_VAR,
                OSMAC_mMSE_VAR[,!(colnames(OSMAC_mMSE_VAR) %in% "Type")],
                OSMAC_mVc_VAR[,!(colnames(OSMAC_mVc_VAR) %in% "Type")])
All_ACC<-rbind(RS_ACC,
                OSMAC_mMSE_ACC[,!(colnames(OSMAC_mMSE_ACC) %in% "Type")],
                OSMAC_mVc_ACC[,!(colnames(OSMAC_mVc_ACC) %in% "Type")])

All_Objects<-ls()
remove(list = All_Objects[startsWith(All_Objects,"OSMAC")])

colnames(All_Bias)[3]<-"Estimated Values"
colnames(All_EMSE)[3]<-"Estimated Values"
colnames(All_Info)[3]<-"Estimated Values"
colnames(All_MSE)[3]<-"Estimated Values"
colnames(All_VAR)[3]<-"Estimated Values"
colnames(All_ACC)[3]<-"Estimated Values"

Final_Data_Identical_r0<-rbind(cbind.data.frame(Metric="Bias",All_Bias),
                               cbind.data.frame(Metric="EMSE",All_EMSE),
                               cbind.data.frame(Metric="Model Information",All_Info),
                               cbind.data.frame(Metric="MSE",All_MSE),
                               cbind.data.frame(Metric="Variance",All_VAR),
                               cbind.data.frame(Metric="Accuracy",All_ACC))

remove(All_Bias,All_EMSE,All_Info,All_MSE,All_VAR,All_ACC)
```


```{r load Non Identical Data}
Old_Labels<-c("Real Model",paste0("Assumed Model ",1:3))
New_Labels<-c("RM",paste0("AM ",1:3))

# OSMAC
load(here("Non_Identical_r0","Summary","Classical",params$Model_Path,"Data","Efficiency",
          "No_Correlated_Covariate_OSMAC.RData"))

## mMSE
for (i in 1:length(Old_Labels)) 
{
  All_Bias$Model[All_Bias$Model==Old_Labels[i] & All_Bias$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
  All_EMSE$Model[All_EMSE$Model==Old_Labels[i] & All_Bias$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
  All_Info$Model[All_Info$Model==Old_Labels[i] & All_Bias$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
  All_MSE$Model[All_MSE$Model==Old_Labels[i] & All_Bias$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
  All_VAR$Model[All_VAR$Model==Old_Labels[i] & All_Bias$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
  Accuracy_Data$Model[Accuracy_Data$Model==Old_Labels[i] & All_Bias$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
}

OSMAC_mMSE_Bias<-All_Bias[All_Bias$Type == "mMSE",] 
OSMAC_mMSE_EMSE<-All_EMSE[All_EMSE$Type == "mMSE",]
OSMAC_mMSE_Info<-All_Info[All_Info$Type == "mMSE",]
OSMAC_mMSE_MSE<-All_MSE[All_MSE$Type == "mMSE",]
OSMAC_mMSE_VAR<-All_VAR[All_VAR$Type == "mMSE",]
OSMAC_mMSE_ACC<-Accuracy_Data[Accuracy_Data$Type == "mMSE",]

## mVc
for (i in 1:length(Old_Labels)) 
{
  All_Bias$Model[All_Bias$Model==Old_Labels[i] & All_Bias$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
  All_EMSE$Model[All_EMSE$Model==Old_Labels[i] & All_Bias$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
  All_Info$Model[All_Info$Model==Old_Labels[i] & All_Bias$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
  All_MSE$Model[All_MSE$Model==Old_Labels[i] & All_Bias$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
  All_VAR$Model[All_VAR$Model==Old_Labels[i] & All_Bias$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
  Accuracy_Data$Model[Accuracy_Data$Model==Old_Labels[i] & All_Bias$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
}

OSMAC_mVc_Bias<-All_Bias[All_Bias$Type == "mVc",] 
OSMAC_mVc_EMSE<-All_EMSE[All_EMSE$Type == "mVc",]
OSMAC_mVc_Info<-All_Info[All_Info$Type == "mVc",]
OSMAC_mVc_MSE<-All_MSE[All_MSE$Type == "mVc",]
OSMAC_mVc_VAR<-All_VAR[All_VAR$Type == "mVc",]
OSMAC_mVc_ACC<-Accuracy_Data[Accuracy_Data$Type == "mVc",]

remove(All_Bias,All_EMSE,All_MSE,All_Info,All_VAR)

# OSMAC Model Free
load(here("Non_Identical_r0","Summary","Classical",params$Model_Path,"Data","Efficiency",
          "No_Correlated_Covariate_OSMAC_MF.RData"))

Accuracy_Data<-cbind(Model="Real Model",Accuracy_Data)

Old_Labels[1]<-c("Real Model")

All_Bias<-All_Bias[All_Bias$Model==Old_Labels[1],]
All_EMSE<-All_EMSE[All_EMSE$Model==Old_Labels[1],]
All_Info<-All_Info[All_Info$Model==Old_Labels[1],]
All_MSE<-All_MSE[All_MSE$Model==Old_Labels[1],]
All_VAR<-All_VAR[All_VAR$Model==Old_Labels[1],]
Accuracy_Data<-Accuracy_Data[Accuracy_Data$Model==Old_Labels[1],]

## mMSE
All_Bias$Model[All_Bias$Type == "mMSE"] <-paste0("OSMAC mMSE MF")
All_EMSE$Model[All_EMSE$Type == "mMSE"] <-paste0("OSMAC mMSE MF")
All_Info$Model[All_Info$Type == "mMSE"] <-paste0("OSMAC mMSE MF")
All_MSE$Model[All_MSE$Type == "mMSE"] <-paste0("OSMAC mMSE MF")
All_VAR$Model[All_VAR$Type == "mMSE"] <-paste0("OSMAC mMSE MF")
Accuracy_Data$Model[Accuracy_Data$Type == "mMSE"] <-paste0("OSMAC mMSE MF")

OSMAC_MF_mMSE_Bias<-All_Bias[All_Bias$Type == "mMSE",] 
OSMAC_MF_mMSE_EMSE<-All_EMSE[All_EMSE$Type == "mMSE",]
OSMAC_MF_mMSE_Info<-All_Info[All_Info$Type == "mMSE",]
OSMAC_MF_mMSE_MSE<-All_MSE[All_MSE$Type == "mMSE",]
OSMAC_MF_mMSE_VAR<-All_VAR[All_VAR$Type == "mMSE",]
OSMAC_MF_mMSE_ACC<-Accuracy_Data[Accuracy_Data$Type == "mMSE",]

## mVc
All_Bias$Model[All_Bias$Type == "mVc"] <-paste0("OSMAC mVc MF")
All_EMSE$Model[All_EMSE$Type == "mVc"] <-paste0("OSMAC mVc MF")
All_Info$Model[All_Info$Type == "mVc"] <-paste0("OSMAC mVc MF")
All_MSE$Model[All_MSE$Type == "mVc"] <-paste0("OSMAC mVc MF")
All_VAR$Model[All_VAR$Type == "mVc"] <-paste0("OSMAC mVc MF")
Accuracy_Data$Model[Accuracy_Data$Type == "mVc"] <-paste0("OSMAC mVc MF")

OSMAC_MF_mVc_Bias<-All_Bias[All_Bias$Type == "mVc",] 
OSMAC_MF_mVc_EMSE<-All_EMSE[All_EMSE$Type == "mVc",]
OSMAC_MF_mVc_Info<-All_Info[All_Info$Type == "mVc",]
OSMAC_MF_mVc_MSE<-All_MSE[All_MSE$Type == "mVc",]
OSMAC_MF_mVc_VAR<-All_VAR[All_VAR$Type == "mVc",]
OSMAC_MF_mVc_ACC<-Accuracy_Data[Accuracy_Data$Type == "mVc",]

remove(All_Bias,All_EMSE,All_MSE,All_Info,All_VAR,Accuracy_Data)

# All elements
All_Bias<-rbind(RS_Bias,
                OSMAC_mMSE_Bias[,!(colnames(OSMAC_mMSE_Bias) %in% "Type")],
                OSMAC_mVc_Bias[,!(colnames(OSMAC_mVc_Bias) %in% "Type")],
                OSMAC_MF_mMSE_Bias[,!(colnames(OSMAC_MF_mMSE_Bias) %in% "Type")],
                OSMAC_MF_mVc_Bias[,!(colnames(OSMAC_MF_mVc_Bias) %in% "Type")])
All_EMSE<-rbind(RS_EMSE,
                OSMAC_mMSE_EMSE[,!(colnames(OSMAC_mMSE_EMSE) %in% "Type")],
                OSMAC_mVc_EMSE[,!(colnames(OSMAC_mVc_EMSE) %in% "Type")],
                OSMAC_MF_mMSE_EMSE[,!(colnames(OSMAC_MF_mMSE_EMSE) %in% "Type")],
                OSMAC_MF_mVc_EMSE[,!(colnames(OSMAC_MF_mVc_EMSE) %in% "Type")])
All_MSE<-rbind(RS_MSE,
               OSMAC_mMSE_MSE[,!(colnames(OSMAC_mMSE_MSE) %in% "Type")],
                OSMAC_mVc_MSE[,!(colnames(OSMAC_mVc_MSE) %in% "Type")],
                OSMAC_MF_mMSE_MSE[,!(colnames(OSMAC_MF_mMSE_MSE) %in% "Type")],
                OSMAC_MF_mVc_MSE[,!(colnames(OSMAC_MF_mVc_MSE) %in% "Type")])
All_Info<-rbind(RS_Info,
                OSMAC_mMSE_Info[,!(colnames(OSMAC_mMSE_Info) %in% "Type")],
                OSMAC_mVc_Info[,!(colnames(OSMAC_mVc_Info) %in% "Type")],
                OSMAC_MF_mMSE_Info[,!(colnames(OSMAC_MF_mMSE_Info) %in% "Type")],
                OSMAC_MF_mVc_Info[,!(colnames(OSMAC_MF_mVc_Info) %in% "Type")])
All_VAR<-rbind(RS_VAR,
               OSMAC_mMSE_VAR[,!(colnames(OSMAC_mMSE_VAR) %in% "Type")],
               OSMAC_mVc_VAR[,!(colnames(OSMAC_mVc_VAR) %in% "Type")],
               OSMAC_MF_mMSE_VAR[,!(colnames(OSMAC_MF_mMSE_VAR) %in% "Type")],
               OSMAC_MF_mVc_VAR[,!(colnames(OSMAC_MF_mVc_VAR) %in% "Type")])
All_ACC<-rbind(RS_ACC,
               OSMAC_mMSE_ACC[,!(colnames(OSMAC_mMSE_ACC) %in% "Type")],
               OSMAC_mVc_ACC[,!(colnames(OSMAC_mVc_ACC) %in% "Type")],
               OSMAC_MF_mMSE_ACC[,!(colnames(OSMAC_MF_mMSE_ACC) %in% "Type")],
               OSMAC_MF_mVc_ACC[,!(colnames(OSMAC_MF_mVc_ACC) %in% "Type")])

All_Objects<-ls()
remove(list = All_Objects[startsWith(All_Objects,"OSMAC")])
remove(list = All_Objects[startsWith(All_Objects,"RS")])

All_Bias$Model<-factor(All_Bias$Model,levels=c("RS RM","RS AM 1","RS AM 2","RS AM 3",
                                               "OSMAC mMSE RM","OSMAC mVc RM",
                                               "OSMAC mMSE AM 1","OSMAC mVc AM 1",
                                               "OSMAC mMSE AM 2","OSMAC mVc AM 2",
                                               "OSMAC mMSE AM 3","OSMAC mVc AM 3",
                                               "OSMAC mMSE MF","OSMAC mVc MF"))
All_EMSE$Model<-factor(All_EMSE$Model,levels=c("RS RM","RS AM 1","RS AM 2","RS AM 3",
                                               "OSMAC mMSE RM","OSMAC mVc RM",
                                               "OSMAC mMSE AM 1","OSMAC mVc AM 1",
                                               "OSMAC mMSE AM 2","OSMAC mVc AM 2",
                                               "OSMAC mMSE AM 3","OSMAC mVc AM 3",
                                               "OSMAC mMSE MF","OSMAC mVc MF"))
All_Info$Model<-factor(All_Info$Model,levels=c("RS RM","RS AM 1","RS AM 2","RS AM 3",
                                               "OSMAC mMSE RM","OSMAC mVc RM",
                                               "OSMAC mMSE AM 1","OSMAC mVc AM 1",
                                               "OSMAC mMSE AM 2","OSMAC mVc AM 2",
                                               "OSMAC mMSE AM 3","OSMAC mVc AM 3",
                                               "OSMAC mMSE MF","OSMAC mVc MF"))
All_MSE$Model<-factor(All_MSE$Model,levels=c("RS RM","RS AM 1","RS AM 2","RS AM 3",
                                             "OSMAC mMSE RM","OSMAC mVc RM",
                                             "OSMAC mMSE AM 1","OSMAC mVc AM 1",
                                             "OSMAC mMSE AM 2","OSMAC mVc AM 2",
                                             "OSMAC mMSE AM 3","OSMAC mVc AM 3",
                                             "OSMAC mMSE MF","OSMAC mVc MF"))
All_VAR$Model<-factor(All_VAR$Model,levels=c("RS RM","RS AM 1","RS AM 2","RS AM 3",
                                             "OSMAC mMSE RM","OSMAC mVc RM",
                                             "OSMAC mMSE AM 1","OSMAC mVc AM 1",
                                             "OSMAC mMSE AM 2","OSMAC mVc AM 2",
                                             "OSMAC mMSE AM 3","OSMAC mVc AM 3",
                                             "OSMAC mMSE MF","OSMAC mVc MF"))
All_ACC$Model<-factor(All_ACC$Model,levels=c("RS RM","RS AM 1","RS AM 2","RS AM 3",
                                             "OSMAC mMSE RM","OSMAC mVc RM",
                                             "OSMAC mMSE AM 1","OSMAC mVc AM 1",
                                             "OSMAC mMSE AM 2","OSMAC mVc AM 2",
                                             "OSMAC mMSE AM 3","OSMAC mVc AM 3",
                                             "OSMAC mMSE MF","OSMAC mVc MF"))

colnames(All_Bias)[3]<-"Estimated Values"
colnames(All_EMSE)[3]<-"Estimated Values"
colnames(All_Info)[3]<-"Estimated Values"
colnames(All_MSE)[3]<-"Estimated Values"
colnames(All_VAR)[3]<-"Estimated Values"
colnames(All_ACC)[3]<-"Estimated Values"

Final_Data_Non_Identical_r0<-rbind(cbind.data.frame(Metric="Bias",All_Bias),
                                   cbind.data.frame(Metric="EMSE",All_EMSE),
                                   cbind.data.frame(Metric="Model Information",All_Info),
                                   cbind.data.frame(Metric="MSE",All_MSE),
                                   cbind.data.frame(Metric="Variance",All_VAR),
                                   cbind.data.frame(Metric="MSE Y",All_ACC))

remove(All_Bias,All_EMSE,All_Info,All_MSE,All_VAR)
```

```{r Identical r0 Plots}
# mMSE models Colors
Selected_mMSE<-c(#"RS RM",
                 #"RS AM 1","RS AM 2","RS AM 3",
                 "OSMAC mMSE RM",
                 "OSMAC mMSE AM 1","OSMAC mMSE AM 2","OSMAC mMSE AM 3",
                 "OSMAC mMSE MF")
Colors_mMSE<-c(#"#88CCEE",
               #"#A6C3D3","#5D92B0","#35586C", 
               "#FFC4D8", 
               "#E28490","#BB2C3E","#55141C", 
               "#DDCC77")
# mvc models
Selected_mVc<-c(#"RS RM",
                #"RS AM 1","RS AM 2","RS AM 3",
                "OSMAC mVc RM",
                "OSMAC mVc AM 1","OSMAC mVc AM 2","OSMAC mVc AM 3",
                "OSMAC mVc MF")
Colors_mVc<-c(#"#88CCEE",
              #"#A6C3D3","#5D92B0","#35586C", 
              "#FFC4D8", 
               "#E28490","#BB2C3E","#55141C", 
               "#DDCC77")

Final_Data<-rbind(cbind(Data="Identical r0",Final_Data_Identical_r0),
                  cbind(Data="Non Identical r0",Final_Data_Non_Identical_r0))

Final_Data[(Final_Data$Model %in% Selected_mMSE) & (Final_Data$Metric == "MSE"),] %>%
  ggplot(.,aes(x=Subsample_Size,y=`Estimated Values`,color=Model))+
  geom_point(size=1.75)+geom_line(size=1)+
  scale_color_manual(values=Colors_mMSE)+
  theme_light()+xlab("Sub sample size")+
  ggtitle("Comparing Simulated MSE",subtitle = "mMSE")+
  ylab("Estimated Values")+facet_wrap(~Data,scales = "free_y")->p1

Final_Data[(Final_Data$Model %in% Selected_mVc) & (Final_Data$Metric == "MSE"),] %>%
  ggplot(.,aes(x=Subsample_Size,y=`Estimated Values`,color=Model))+
  geom_point(size=1.75)+geom_line(size=1)+
  scale_color_manual(values=Colors_mMSE)+
  theme_light()+xlab("Sub sample size")+
  ggtitle("Comparing Simulated MSE",subtitle = "mVc")+
  ylab("Estimated Values")+facet_wrap(~Data,scales = "free_y")->p2

Final_Data[(Final_Data$Model %in% Selected_mMSE) & (Final_Data$Metric == "Model Information"),] %>%
  ggplot(.,aes(x=Subsample_Size,y=`Estimated Values`,color=Model))+
  geom_point(size=1.75)+geom_line(size=1)+
  scale_color_manual(values=Colors_mMSE)+
  theme_light()+xlab("Sub sample size")+
  ggtitle("Comparing Estimated Model Information",subtitle = "mMSE")+
  ylab("Estimated Values")+facet_wrap(~Data,scales = "free_y")->p3

Final_Data[(Final_Data$Model %in% Selected_mVc) & (Final_Data$Metric == "Model Information"),] %>%
  ggplot(.,aes(x=Subsample_Size,y=`Estimated Values`,color=Model))+
  geom_point(size=1.75)+geom_line(size=1)+
  scale_color_manual(values=Colors_mMSE)+
  theme_light()+xlab("Sub sample size")+
  ggtitle("Comparing Estimated Model Information",subtitle = "mVc")+
  ylab("Estimated Values")+facet_wrap(~Data,scales = "free_y")->p4

Final_Data[(Final_Data$Model %in% Selected_mMSE) & (Final_Data$Metric == "MSE Y"),] %>%
  ggplot(.,aes(x=Subsample_Size,y=`Estimated Values`,color=Model))+
  geom_point(size=1.75)+geom_line(size=1)+
  scale_color_manual(values=Colors_mMSE)+
  theme_light()+xlab("Sub sample size")+
  ggtitle("Comparing Average MSE Y",subtitle = "mMSE")+
  ylab("Estimated Values")+facet_wrap(~Data,scales = "free_y")->p5

Final_Data[(Final_Data$Model %in% Selected_mVc) & (Final_Data$Metric == "MSE Y"),] %>%
  ggplot(.,aes(x=Subsample_Size,y=`Estimated Values`,color=Model))+
  geom_point(size=1.75)+geom_line(size=1)+
  scale_color_manual(values=Colors_mMSE)+
  theme_light()+xlab("Sub sample size")+
  ggtitle("Comparing Average MSE Y",subtitle = "mVc")+
  ylab("Estimated Values")+facet_wrap(~Data,scales = "free_y")->p6

ggarrange(p1,p2,p3,p4,nrow = 4)
ggarrange(p5,p6,nrow = 2)
```

```{r Identical r0 Plots with gg.gap,fig.height=4}
SS_Choice<-100*c(10:15)

Final_Data[(Final_Data$Model %in% Selected_mMSE) & (Final_Data$Metric == "MSE") & 
             Final_Data$Subsample_Size %in% SS_Choice,] %>%
  ggplot(.,aes(x=Subsample_Size,y=`Estimated Values`,color=Model))+
  geom_point(size=1.75)+geom_line(size=1)+scale_color_manual(values=Colors_mMSE)+
  theme_light()+xlab("Sub sample size")+
  ggtitle("Comparing Simulated MSE",subtitle = "mMSE")+
  ylab("Estimated Values")+facet_wrap(~Data)->p1_New

Final_Data[(Final_Data$Model %in% Selected_mVc) & (Final_Data$Metric == "MSE") & 
             Final_Data$Subsample_Size %in% SS_Choice,] %>%
  ggplot(.,aes(x=Subsample_Size,y=`Estimated Values`,color=Model))+
  geom_point(size=1.75)+geom_line(size=1)+scale_color_manual(values=Colors_mMSE)+
  theme_light()+xlab("Sub sample size")+
  ggtitle("Comparing Simulated MSE",subtitle = "mVc")+
  ylab("Estimated Values")+facet_wrap(~Data)->p2_New

Final_Data[(Final_Data$Model %in% Selected_mMSE) & (Final_Data$Metric == "Model Information") & 
             Final_Data$Subsample_Size %in% SS_Choice,] %>%
  ggplot(.,aes(x=Subsample_Size,y=`Estimated Values`,color=Model))+
  geom_point(size=1.75)+geom_line(size=1)+scale_color_manual(values=Colors_mMSE)+
  theme_light()+xlab("Sub sample size")+
  ggtitle("Comparing Estimated Model Information",subtitle = "mMSE")+
  ylab("Estimated Values")+facet_wrap(~Data)->p3_New

Final_Data[(Final_Data$Model %in% Selected_mVc) & (Final_Data$Metric == "Model Information") & 
             Final_Data$Subsample_Size %in% SS_Choice,] %>%
  ggplot(.,aes(x=Subsample_Size,y=`Estimated Values`,color=Model))+
  geom_point(size=1.75)+geom_line(size=1)+scale_color_manual(values=Colors_mMSE)+
  theme_light()+xlab("Sub sample size")+
  ggtitle("Comparing Estimated Model Information",subtitle = "mVc")+
  ylab("Estimated Values")+facet_wrap(~Data)->p4_New

Final_Data[(Final_Data$Model %in% Selected_mMSE) & (Final_Data$Metric == "MSE Y") & 
             Final_Data$Subsample_Size %in% SS_Choice,] %>%
  ggplot(.,aes(x=Subsample_Size,y=`Estimated Values`,color=Model))+
  geom_point(size=1.75)+geom_line(size=1)+scale_color_manual(values=Colors_mMSE)+
  theme_light()+xlab("Sub sample size")+
  ggtitle("Comparing Average MSE Y",subtitle = "mMSE")+
  ylab("Estimated Values")+facet_wrap(~Data)->p5_New

Final_Data[(Final_Data$Model %in% Selected_mVc) & (Final_Data$Metric == "MSE Y") & 
             Final_Data$Subsample_Size %in% SS_Choice,] %>%
  ggplot(.,aes(x=Subsample_Size,y=`Estimated Values`,color=Model))+
  geom_point(size=1.75)+geom_line(size=1)+scale_color_manual(values=Colors_mMSE)+
  theme_light()+xlab("Sub sample size")+
  ggtitle("Comparing Average MSE Y",subtitle = "mVc")+
  ylab("Estimated Values")+facet_wrap(~Data)->p6_New
```

```{r All Plots}
ggarrange(p1,p1_New,
          p2,p2_New,nrow = 4)

ggarrange(p5_New,p6_New,nrow = 2)
```