---
title: "Articles_Plots"
author: "Amalan"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,fig.width = 14,fig.height = 16,message = FALSE,warning = FALSE)
library(here)
library(ggplot2)
library(dplyr)
library(tidyr)
library(LaplacesDemon)
library(xtable)
library(flextable)
library(grid)
library(cowplot)
library(linguisticsdown)
library(ggpubr)

```

# Using Uniform Distribution for Data

```{r Load data model 1}
Model_1_SS<-1000

# OSMAC
load(here("Identical_r0","Summary","Model_1","Data","Efficiency","No_Correlated_Covariate_OSMAC_r1.RData"))
remove_stuff<-c(paste0("Assumed New ",1:3))
All_MSE<-All_MSE[!(All_MSE$Model %in% remove_stuff),]
All_MSE_MLE<-All_MSE_MLE[!(All_MSE_MLE$Model %in% remove_stuff),]
All_Info<-All_Info[!(All_Info$Model %in% remove_stuff),]
All_ACC<-Accuracy_Data[!(Accuracy_Data$Model %in% remove_stuff),]

Old_Labels<-c("Real",paste0("Assumed Old ",1:3),"Model Free")
New_Labels<-c("DM",paste0("AM ",1:2),"CM","MR")

## mMSE
for (i in 1:length(Old_Labels)) 
{
  All_Info$Model[All_Info$Model==Old_Labels[i] & All_Info$Type == "mMSE"] <-paste0("mMSE ",New_Labels[i])
  All_MSE$Model[All_MSE$Model==Old_Labels[i] & All_MSE$Type == "mMSE"] <-paste0("mMSE ",New_Labels[i])
  All_MSE_MLE$Model[All_MSE_MLE$Model==Old_Labels[i] & All_MSE_MLE$Type == "mMSE"] <-paste0("mMSE ",New_Labels[i])
  All_ACC$Model[All_ACC$Model==Old_Labels[i] & All_ACC$Type == "mMSE"] <-paste0("mMSE ",New_Labels[i])
}

## mVc
for (i in 1:length(Old_Labels)) 
{
  All_Info$Model[All_Info$Model==Old_Labels[i] & All_Info$Type == "mVc"] <-paste0("mVc ",New_Labels[i])
  All_MSE$Model[All_MSE$Model==Old_Labels[i] & All_MSE$Type == "mVc"] <-paste0("mVc ",New_Labels[i])
  All_MSE_MLE$Model[All_MSE_MLE$Model==Old_Labels[i] & All_MSE_MLE$Type == "mVc"] <-paste0("mVc ",New_Labels[i])
  All_ACC$Model[All_ACC$Model==Old_Labels[i] & All_ACC$Type == "mVc"] <-paste0("mVc ",New_Labels[i])
}

OSMAC_Info<-All_Info
OSMAC_MSE<-All_MSE
OSMAC_MSE_MLE<-All_MSE_MLE
OSMAC_ACC<-All_ACC

remove(All_Bias,All_EMSE,All_MSE,All_Info,All_VAR,Accuracy_Data)

# All elements
All_MSE<-rbind(OSMAC_MSE[,!(colnames(OSMAC_MSE) %in% "Type")])
All_MSE_MLE<-rbind(OSMAC_MSE_MLE[,!(colnames(OSMAC_MSE_MLE) %in% "Type")])
All_Info<-rbind(OSMAC_Info[,!(colnames(OSMAC_Info) %in% "Type")])
All_ACC<-rbind(OSMAC_ACC[,!(colnames(OSMAC_ACC) %in% "Type")])

All_Objects<-ls()
remove(list = All_Objects[startsWith(All_Objects,"OSMAC")])

colnames(All_Info)[3]<-"Estimated Values"
colnames(All_MSE)[3]<-"Estimated Values"
colnames(All_MSE_MLE)[3]<-"Estimated Values"
colnames(All_ACC)[3]<-"Estimated Values"

M1_Identical_r0<-rbind(cbind.data.frame(Covariate="Data Model: x\u2081, x\u2082",Metric="Model Information",
                                        All_Info),
                       cbind.data.frame(Covariate="Data Model: x\u2081, x\u2082",Metric="MSE",
                                        All_MSE),
                       cbind.data.frame(Covariate="Data Model: x\u2081, x\u2082",Metric="MSE for MLE",
                                        All_MSE_MLE),
                       cbind.data.frame(Covariate="Data Model: x\u2081, x\u2082",Metric="Average MSE Y",
                                        All_ACC))

remove(All_Info,All_MSE,RS_Info,RS_MSE,All_ACC)

```

```{r Load data model 2}
Model_2_SS<-1000

# OSMAC
load(here("Identical_r0","Summary","Model_2","Data","Efficiency","No_Correlated_Covariate_OSMAC_r1.RData"))
remove_stuff<-c(paste0("Assumed New ",1:3))
All_MSE<-All_MSE[!(All_MSE$Model %in% remove_stuff),]
All_MSE_MLE<-All_MSE_MLE[!(All_MSE_MLE$Model %in% remove_stuff),]
All_Info<-All_Info[!(All_Info$Model %in% remove_stuff),]
Accuracy_Data<-Accuracy_Data[!(Accuracy_Data$Model %in% remove_stuff),]

Old_Labels<-c("Real",paste0("Assumed Old ",1:3),"Model Free")
New_Labels<-c("DM",paste0("AM ",1:2),"CM","MR")

## mMSE
for (i in 1:length(Old_Labels)) 
{
  All_Info$Model[All_Info$Model==Old_Labels[i] & All_Info$Type == "mMSE"] <-paste0("mMSE ",New_Labels[i])
  All_MSE$Model[All_MSE$Model==Old_Labels[i] & All_MSE$Type == "mMSE"] <-paste0("mMSE ",New_Labels[i])
  All_MSE_MLE$Model[All_MSE_MLE$Model==Old_Labels[i] & All_MSE_MLE$Type == "mMSE"] <-paste0("mMSE ",New_Labels[i])
  Accuracy_Data$Model[Accuracy_Data$Model==Old_Labels[i] & Accuracy_Data$Type == "mMSE"] <-paste0("mMSE ",New_Labels[i])
}

## mVc
for (i in 1:length(Old_Labels)) 
{
  All_Info$Model[All_Info$Model==Old_Labels[i] & All_Info$Type == "mVc"] <-paste0("mVc ",New_Labels[i])
  All_MSE$Model[All_MSE$Model==Old_Labels[i] & All_MSE$Type == "mVc"] <-paste0("mVc ",New_Labels[i])
  All_MSE_MLE$Model[All_MSE_MLE$Model==Old_Labels[i] & All_MSE_MLE$Type == "mVc"] <-paste0("mVc ",New_Labels[i])
  Accuracy_Data$Model[Accuracy_Data$Model==Old_Labels[i] & Accuracy_Data$Type == "mVc"] <-paste0("mVc ",New_Labels[i])
}

OSMAC_Info<-All_Info
OSMAC_MSE<-All_MSE
OSMAC_MSE_MLE<-All_MSE_MLE
OSMAC_ACC<-Accuracy_Data

remove(All_Bias,All_EMSE,All_MSE,All_Info,All_VAR,Accuracy_Data)

# All elements
All_MSE<-rbind(OSMAC_MSE[,!(colnames(OSMAC_MSE) %in% "Type")])
All_MSE_MLE<-rbind(OSMAC_MSE_MLE[,!(colnames(OSMAC_MSE_MLE) %in% "Type")])
All_Info<-rbind(OSMAC_Info[,!(colnames(OSMAC_Info) %in% "Type")])
All_ACC<-rbind(OSMAC_ACC[,!(colnames(OSMAC_ACC) %in% "Type")])

All_Objects<-ls()
remove(list = All_Objects[startsWith(All_Objects,"OSMAC")])

colnames(All_Info)[3]<-"Estimated Values"
colnames(All_MSE_MLE)[3]<-"Estimated Values"
colnames(All_MSE)[3]<-"Estimated Values"
colnames(All_ACC)[3]<-"Estimated Values"

M2_Identical_r0<-rbind(cbind.data.frame(Covariate="Data Model: x\u2081, x\u2082, (x\u2081)\u00B2",Metric="Model Information",
                                        All_Info),
                       cbind.data.frame(Covariate="Data Model: x\u2081, x\u2082, (x\u2081)\u00B2",Metric="MSE",
                                        All_MSE),
                       cbind.data.frame(Covariate="Data Model: x\u2081, x\u2082, (x\u2081)\u00B2",Metric="MSE for MLE",
                                        All_MSE_MLE),
                       cbind.data.frame(Covariate="Data Model: x\u2081, x\u2082, (x\u2081)\u00B2",Metric="Average MSE Y",
                                        All_ACC))

remove(All_Info,All_MSE,RS_Info,RS_MSE,All_ACC)

```

```{r Load data model 3}
Model_3_SS<-1000

# OSMAC
load(here("Identical_r0","Summary","Model_3","Data","Efficiency","No_Correlated_Covariate_OSMAC_r1.RData"))
remove_stuff<-c(paste0("Assumed New ",1:3))
All_MSE<-All_MSE[!(All_MSE$Model %in% remove_stuff),]
All_MSE_MLE<-All_MSE_MLE[!(All_MSE_MLE$Model %in% remove_stuff),]
All_Info<-All_Info[!(All_Info$Model %in% remove_stuff),]
All_ACC<-Accuracy_Data[!(Accuracy_Data$Model %in% remove_stuff),]

Old_Labels<-c("Real",paste0("Assumed Old ",1:3),"Model Free")
New_Labels<-c("DM",paste0("AM ",1:2),"CM","MR")

## mMSE
for (i in 1:length(Old_Labels)) 
{
  All_Info$Model[All_Info$Model==Old_Labels[i] & All_Info$Type == "mMSE"] <-paste0("mMSE ",New_Labels[i])
  All_MSE$Model[All_MSE$Model==Old_Labels[i] & All_MSE$Type == "mMSE"] <-paste0("mMSE ",New_Labels[i])
  All_MSE_MLE$Model[All_MSE_MLE$Model==Old_Labels[i] & All_MSE_MLE$Type == "mMSE"] <-paste0("mMSE ",New_Labels[i])
  All_ACC$Model[All_ACC$Model==Old_Labels[i] & All_ACC$Type == "mMSE"] <-paste0("mMSE ",New_Labels[i])
}

## mVc
for (i in 1:length(Old_Labels)) 
{
  All_Info$Model[All_Info$Model==Old_Labels[i] & All_Info$Type == "mVc"] <-paste0("mVc ",New_Labels[i])
  All_MSE$Model[All_MSE$Model==Old_Labels[i] & All_MSE$Type == "mVc"] <-paste0("mVc ",New_Labels[i])
  All_MSE_MLE$Model[All_MSE_MLE$Model==Old_Labels[i] & All_MSE_MLE$Type == "mVc"] <-paste0("mVc ",New_Labels[i])
  All_ACC$Model[All_ACC$Model==Old_Labels[i] & All_ACC$Type == "mVc"] <-paste0("mVc ",New_Labels[i])
}

OSMAC_Info<-All_Info
OSMAC_MSE<-All_MSE
OSMAC_MSE_MLE<-All_MSE_MLE
OSMAC_ACC<-All_ACC

remove(All_Bias,All_EMSE,All_MSE,All_Info,All_VAR,All_ACC)

# All elements
All_MSE<-rbind(OSMAC_MSE[,!(colnames(OSMAC_MSE) %in% "Type")])
All_MSE_MLE<-rbind(OSMAC_MSE_MLE[,!(colnames(OSMAC_MSE_MLE) %in% "Type")])
All_Info<-rbind(OSMAC_Info[,!(colnames(OSMAC_Info) %in% "Type")])
All_ACC<-rbind(OSMAC_ACC[,!(colnames(OSMAC_ACC) %in% "Type")])

All_Objects<-ls()
remove(list = All_Objects[startsWith(All_Objects,"OSMAC")])

colnames(All_Info)[3]<-"Estimated Values"
colnames(All_MSE)[3]<-"Estimated Values"
colnames(All_MSE_MLE)[3]<-"Estimated Values"
colnames(All_ACC)[3]<-"Estimated Values"

M3_Identical_r0<-rbind(cbind.data.frame(Covariate="Data Model: x\u2081, x\u2082, (x\u2082)\u00B2",Metric="Model Information",
                                        All_Info),
                       cbind.data.frame(Covariate="Data Model: x\u2081, x\u2082, (x\u2082)\u00B2",Metric="MSE",
                                        All_MSE),
                       cbind.data.frame(Covariate="Data Model: x\u2081, x\u2082, (x\u2082)\u00B2",Metric="MSE for MLE",
                                        All_MSE_MLE),
                       cbind.data.frame(Covariate="Data Model: x\u2081, x\u2082, (x\u2082)\u00B2",Metric="Average MSE Y",
                                        All_ACC))

remove(All_Info,All_MSE,RS_Info,RS_MSE)

```

```{r Load data model 4}
Model_4_SS<-1000

# OSMAC
load(here("Identical_r0","Summary","Model_4","Data","Efficiency","No_Correlated_Covariate_OSMAC_r1.RData"))
remove_stuff<-c(paste0("Assumed New ",1:3))
All_MSE<-All_MSE[!(All_MSE$Model %in% remove_stuff),]
All_MSE_MLE<-All_MSE_MLE[!(All_MSE_MLE$Model %in% remove_stuff),]
All_Info<-All_Info[!(All_Info$Model %in% remove_stuff),]
All_ACC<-Accuracy_Data[!(Accuracy_Data$Model %in% remove_stuff),]

Old_Labels<-c("Real",paste0("Assumed Old ",1:3),"Model Free")
New_Labels<-c("DM",paste0("AM ",1:3),"MR")

## mMSE
for (i in 1:length(Old_Labels)) 
{
  All_Info$Model[All_Info$Model==Old_Labels[i] & All_Info$Type == "mMSE"] <-paste0("mMSE ",New_Labels[i])
  All_MSE$Model[All_MSE$Model==Old_Labels[i] & All_MSE$Type == "mMSE"] <-paste0("mMSE ",New_Labels[i])
  All_MSE_MLE$Model[All_MSE_MLE$Model==Old_Labels[i] & All_MSE_MLE$Type == "mMSE"] <-paste0("mMSE ",New_Labels[i])
  All_ACC$Model[All_ACC$Model==Old_Labels[i] & All_ACC$Type == "mMSE"] <-paste0("mMSE ",New_Labels[i])
}

## mVc
for (i in 1:length(Old_Labels)) 
{
  All_Info$Model[All_Info$Model==Old_Labels[i] & All_Info$Type == "mVc"] <-paste0("mVc ",New_Labels[i])
  All_MSE$Model[All_MSE$Model==Old_Labels[i] & All_MSE$Type == "mVc"] <-paste0("mVc ",New_Labels[i])
  All_MSE_MLE$Model[All_MSE_MLE$Model==Old_Labels[i] & All_MSE_MLE$Type == "mVc"] <-paste0("mVc ",New_Labels[i])
  All_ACC$Model[All_ACC$Model==Old_Labels[i] & All_ACC$Type == "mVc"] <-paste0("mVc ",New_Labels[i])
}

OSMAC_Info<-All_Info
OSMAC_MSE<-All_MSE
OSMAC_MSE_MLE<-All_MSE_MLE
OSMAC_ACC<-All_ACC

remove(All_Bias,All_EMSE,All_MSE,All_Info,All_VAR,All_ACC)

# All elements
All_MSE<-rbind(OSMAC_MSE[,!(colnames(OSMAC_MSE) %in% "Type")])
All_MSE_MLE<-rbind(OSMAC_MSE_MLE[,!(colnames(OSMAC_MSE_MLE) %in% "Type")])
All_Info<-rbind(OSMAC_Info[,!(colnames(OSMAC_Info) %in% "Type")])
All_ACC<-rbind(OSMAC_ACC[,!(colnames(OSMAC_ACC) %in% "Type")])

All_Objects<-ls()
remove(list = All_Objects[startsWith(All_Objects,"OSMAC")])

colnames(All_Info)[3]<-"Estimated Values"
colnames(All_MSE)[3]<-"Estimated Values"
colnames(All_MSE_MLE)[3]<-"Estimated Values"
colnames(All_ACC)[3]<-"Estimated Values"

M4_Identical_r0<-rbind(cbind.data.frame(Covariate="Data Model: x\u2081, x\u2082, (x\u2081)\u00B2, (x\u2082)\u00B2",
                                        Metric="Model Information",All_Info),
                       cbind.data.frame(Covariate="Data Model: x\u2081, x\u2082, (x\u2081)\u00B2, (x\u2082)\u00B2",
                                        Metric="MSE",All_MSE),
                       cbind.data.frame(Covariate="Data Model: x\u2081, x\u2082, (x\u2081)\u00B2, (x\u2082)\u00B2",
                                        Metric="MSE for MLE",All_MSE_MLE),
                       cbind.data.frame(Covariate="Data Model: x\u2081, x\u2082, (x\u2081)\u00B2, (x\u2082)\u00B2",
                                        Metric="Average MSE Y",All_ACC))

remove(All_Info,All_MSE,RS_Info,RS_MSE,RS_ACC)

```

```{r combine data and plot,fig.width = 8,fig.height = 12}
Identical_ro<-rbind(M1_Identical_r0,M2_Identical_r0,
                    M3_Identical_r0,M4_Identical_r0)

Identical_ro$Covariate<-factor(Identical_ro$Covariate,
                               levels = c("Data Model: x\u2081, x\u2082",
                                          "Data Model: x\u2081, x\u2082, (x\u2081)\u00B2",
                                          "Data Model: x\u2081, x\u2082, (x\u2082)\u00B2",
                                          "Data Model: x\u2081, x\u2082, (x\u2081)\u00B2, (x\u2082)\u00B2"),
                               labels = c(expression("Data Model: "*X[1]*", "*X[2]),
                                          expression("Data Model: "*X[1]*", "*X[2]*", "*X[1]^{2}),
                                          expression("Data Model: "*X[1]*", "*X[2]*", "*X[2]^{2}),
                                          expression("Data Model: "*X[1]*", "*X[2]*", "*X[1]^{2}*", "*X[2]^{2})))

Identical_ro$Model<-factor(Identical_ro$Model,
                           levels = c("mMSE DM","mMSE AM 1","mMSE AM 2","mMSE AM 3","mMSE CM",
                                      "mVc DM","mVc AM 1","mVc AM 2","mVc AM 3","mVc CM",
                                      "mMSE MR","mVc MR"))

Identical_ro$Model<-recode_factor(Identical_ro$Model,
                                  `mMSE DM`="Optimal subsampling mMSE: Data Model",
                                  `mMSE AM 1`="Optimal subsampling mMSE: Incorrect Model 1",
                                  `mMSE AM 2`="Optimal subsampling mMSE: Incorrect Model 2",
                                  `mMSE AM 3`="Optimal subsampling mMSE: Incorrect Model 3",
                                  `mMSE CM` = "Optimal subsampling mMSE: Complex Model",
                                  `mVc DM`="Optimal subsampling mVc: Data Model",
                                  `mVc AM 1`="Optimal subsampling mVc: Incorrect Model 1",
                                  `mVc AM 2`="Optimal subsampling mVc: Incorrect Model 2",
                                  `mVc AM 3`="Optimal subsampling mVc: Incorrect Model 3",
                                  `mVc CM`="Optimal subsampling mVc: Complex Model",
                                  `mMSE MR`="Model Robust subsampling mMSE: Data Model",
                                  `mVc MR`="Model Robust subsampling mVc: Data Model")

Selected_Models_mMSE<-c("Optimal subsampling mMSE: Data Model",
                        "Optimal subsampling mMSE: Incorrect Model 1",
                        "Optimal subsampling mMSE: Incorrect Model 2",
                        "Optimal subsampling mMSE: Incorrect Model 3",
                        "Optimal subsampling mMSE: Complex Model",
                        "Model Robust subsampling mMSE: Data Model")

# Colors_mMSE<-c("#FFC4D8","#E28490","#BB2C3E","#55141C",
#                "#DDCC77")

Colors_mMSE<-c("#cc0000", 
               "#ff578a","#ff578a","#ff578a","#603BDE",
               "darkgreen")
                  
LineType_mMSE<-c("dashed",
                 "dotted","dotted","dotted","dotdash",
                 "solid")
      
ShapeType_mMSE<-c(1,
                  4,4,4,3,
                  8)

Selected_Models_mVc<-c("Optimal subsampling mVc: Data Model",
                       "Optimal subsampling mVc: Incorrect Model 1",
                       "Optimal subsampling mVc: Incorrect Model 2",
                       "Optimal subsampling mVc: Incorrect Model 3",
                       "Optimal subsampling mVc: Complex Model",
                       "Model Robust subsampling mVc: Data Model")

# Colors_mVc<-Colors_mVc<-c("#FFC4D8","#E28490","#BB2C3E","#55141C", 
#                           "#DDCC77")

Colors_mVc<-c("#cc0000", 
              "#ff578a","#ff578a","#ff578a","#603BDE",
              "darkgreen")

LineType_mVc<-c("dashed",
                "dotted","dotted","dotted","dotdash",
                "solid")

ShapeType_mVc<-c(1,
                 4,4,4,3,
                 8)

Theme_special<-function()
{
  theme(legend.key.width=unit(1,"cm"),
        axis.text.x = element_text(color = "black",size=12, angle = 45, hjust=0.75), #, vjust = 0.5
        axis.text.y = element_text(color = "black",size=12), #, vjust = 0.5, hjust=1
        strip.text = element_text(colour = "black",size = 12,face="bold"),
        panel.grid.minor.x = element_blank(),
        axis.title= element_text(color = "black",face = "bold",size = 12),
        legend.text = element_text(color = "black", size=11),
        legend.position = "bottom",
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-1,-2,-1,-2)) 
}

#Identical_ro<-Identical_ro[Identical_ro$Subsample_Size %in% seq(100,1000,100),]

Identical_ro[Identical_ro$Metric=="Model Information" & Identical_ro$Model %in% Selected_Models_mMSE,] %>%
  ggplot(.,aes(x=Subsample_Size,y=`Estimated Values`,color=Model,linetype=Model,shape=Model))+
  scale_x_continuous(labels = unique(Identical_ro$Subsample_Size),
                     breaks = unique(Identical_ro$Subsample_Size))+
  geom_point(size=1.25)+geom_line(size=0.75)+
  scale_color_manual(values=Colors_mMSE)+
  scale_linetype_manual(values=LineType_mMSE)+
  scale_shape_manual(values = ShapeType_mMSE)+
  facet_wrap(~Covariate,scales = "free_y",ncol = 4,labeller = label_parsed)+
  xlab(expression(paste(r[0],'+ r = 1000 and ',r[0])))+
  ylab("Average Model Information")+expand_limits(y = 0)+
  scale_y_continuous(breaks = scales::pretty_breaks(n = length(unique(Identical_ro$Subsample_Size))/2))+
  theme_bw()+guides(colour = guide_legend(nrow = 3))+Theme_special()->Temp_plot_mMSE

Temp_legend_mMSE<-get_legend(Temp_plot_mMSE)

Identical_ro[Identical_ro$Metric=="Model Information" & Identical_ro$Model %in% Selected_Models_mVc,] %>%
  ggplot(.,aes(x=Subsample_Size,y=`Estimated Values`,color=Model,linetype=Model,shape=Model))+
  scale_x_continuous(labels = unique(Identical_ro$Subsample_Size),
                     breaks = unique(Identical_ro$Subsample_Size))+
  geom_point(size=1.25)+geom_line(size=0.75)+
  scale_color_manual(values=Colors_mVc)+
  scale_linetype_manual(values=LineType_mVc)+
  scale_shape_manual(values = ShapeType_mVc)+
  facet_wrap(~Covariate,scales = "free_y",ncol = 4,labeller = label_parsed)+
  xlab(expression(paste(r[0],'+ r = 1000 and ',r[0])))+
  ylab("Average Model Information")+expand_limits(y = 0)+
  scale_y_continuous(breaks = scales::pretty_breaks(n = length(unique(Identical_ro$Subsample_Size))/2))+
  theme_bw()+guides(colour = guide_legend(nrow = 3))+Theme_special()->Temp_plot_mVc

Temp_legend_mVc<-get_legend(Temp_plot_mVc)

Identical_ro[Identical_ro$Metric=="Model Information" & Identical_ro$Model %in% Selected_Models_mMSE,] %>%
  ggplot(.,aes(x=Subsample_Size,y=log(`Estimated Values`),color=Model,linetype=Model,shape=Model))+
  scale_x_continuous(labels = unique(Identical_ro$Subsample_Size),
                     breaks = unique(Identical_ro$Subsample_Size))+
  geom_point(size=1.25)+geom_line(size=0.75)+
  scale_color_manual(values=Colors_mMSE)+
  scale_linetype_manual(values=LineType_mMSE)+
  scale_shape_manual(values = ShapeType_mMSE)+
  facet_wrap(~Covariate,scales = "free_y",ncol = 2,labeller = label_parsed)+
  xlab(expression(paste(r[0],'+ r = 1000 and ',r[0])))+
  ylab("log(Average Model Information)")+#expand_limits(y = 0)+
  scale_y_continuous(breaks = scales::pretty_breaks(n = length(unique(Identical_ro$Subsample_Size))/2))+
  theme_bw()+Theme_special()->p1

Identical_ro[Identical_ro$Metric=="Model Information" & Identical_ro$Model %in% Selected_Models_mVc,] %>%
  ggplot(.,aes(x=Subsample_Size,y=log(`Estimated Values`),color=Model,linetype=Model,shape=Model))+
  scale_x_continuous(labels = unique(Identical_ro$Subsample_Size),
                     breaks = unique(Identical_ro$Subsample_Size))+
  geom_point(size=1.25)+geom_line(size=0.75)+
  scale_color_manual(values=Colors_mVc)+
  scale_linetype_manual(values=LineType_mVc)+
  scale_shape_manual(values = ShapeType_mVc)+
  facet_wrap(~Covariate,scales = "free_y",ncol = 2,labeller = label_parsed)+
  xlab(expression(paste(r[0],'+ r = 1000 and ',r[0])))+
  ylab("log(Average Model Information)")+#expand_limits(y = 0)+
  scale_y_continuous(breaks = scales::pretty_breaks(n = length(unique(Identical_ro$Subsample_Size))/2))+
  theme_bw()+Theme_special()->p2
  
Identical_ro[Identical_ro$Metric=="MSE" & Identical_ro$Model %in% Selected_Models_mMSE,] %>%
  ggplot(.,aes(x=Subsample_Size,y=log(`Estimated Values`),color=Model,linetype=Model,shape=Model))+
  scale_x_continuous(labels = unique(Identical_ro$Subsample_Size),
                     breaks = unique(Identical_ro$Subsample_Size))+
  geom_point(size=1.25)+geom_line(size=0.75)+
  scale_color_manual(values=Colors_mMSE)+
  scale_linetype_manual(values=LineType_mMSE)+
  scale_shape_manual(values = ShapeType_mMSE)+
  facet_wrap(~Covariate,scales = "free_y",ncol = 2,labeller = label_parsed)+
  xlab(expression(paste(r[0],'+ r = 1000 and ',r[0])))+
  ylab("log(SMSE)")+#expand_limits(y = 0)+
  scale_y_continuous(breaks = scales::pretty_breaks(n = length(unique(Identical_ro$Subsample_Size))/2))+
  theme_bw()+Theme_special()->p3


Identical_ro[Identical_ro$Metric=="MSE" & Identical_ro$Model %in% Selected_Models_mVc,] %>%
  ggplot(.,aes(x=Subsample_Size,y=log(`Estimated Values`),color=Model,linetype=Model,shape=Model))+
  scale_x_continuous(labels = unique(Identical_ro$Subsample_Size),
                     breaks = unique(Identical_ro$Subsample_Size))+
  geom_point(size=1.25)+geom_line(size=0.75)+
  scale_color_manual(values=Colors_mVc)+
  scale_linetype_manual(values=LineType_mVc)+
  scale_shape_manual(values = ShapeType_mVc)+
  facet_wrap(~Covariate,scales = "free_y",ncol = 2,labeller = label_parsed)+
  xlab(expression(paste(r[0],'+ r = 1000 and ',r[0])))+
  ylab("log(SMSE)")+#expand_limits(y = 0)+
  scale_y_continuous(breaks = scales::pretty_breaks(n = length(unique(Identical_ro$Subsample_Size))/2))+
  theme_bw()+Theme_special()->p4

Identical_ro[Identical_ro$Metric=="Average MSE Y" & Identical_ro$Model %in% Selected_Models_mMSE,] %>%
  ggplot(.,aes(x=Subsample_Size,y=log(`Estimated Values`),color=Model,linetype=Model,shape=Model))+
  scale_x_continuous(labels = unique(Identical_ro$Subsample_Size),
                     breaks = unique(Identical_ro$Subsample_Size))+
  geom_point(size=1.25)+geom_line(size=0.75)+
  scale_color_manual(values=Colors_mMSE)+
  scale_linetype_manual(values=LineType_mMSE)+
  scale_shape_manual(values = ShapeType_mMSE)+
  facet_wrap(~Covariate,scales = "free_y",ncol = 2,labeller = label_parsed)+
  xlab(expression(paste(r[0],'+ r = 1000 and ',r[0])))+
  ylab("log(Average MSE of Y)")+#expand_limits(y = 0)+
  scale_y_continuous(breaks = scales::pretty_breaks(n = length(unique(Identical_ro$Subsample_Size))/2))+
  theme_bw()+Theme_special()->p5


Identical_ro[Identical_ro$Metric=="Average MSE Y" & Identical_ro$Model %in% Selected_Models_mVc,] %>%
  ggplot(.,aes(x=Subsample_Size,y=log(`Estimated Values`),color=Model,linetype=Model,shape=Model))+
  scale_x_continuous(labels = unique(Identical_ro$Subsample_Size),
                     breaks = unique(Identical_ro$Subsample_Size))+
  geom_point(size=1.25)+geom_line(size=0.75)+
  scale_color_manual(values=Colors_mVc)+
  scale_linetype_manual(values=LineType_mVc)+
  scale_shape_manual(values = ShapeType_mVc)+
  facet_wrap(~Covariate,scales = "free_y",ncol = 2,labeller = label_parsed)+
  xlab(expression(paste(r[0],'+ r = 1000 and ',r[0])))+
  ylab("log(Average MSE of Y)")+#expand_limits(y = 0)+
  scale_y_continuous(breaks = scales::pretty_breaks(n = length(unique(Identical_ro$Subsample_Size))/2))+
  theme_bw()+Theme_special()->p6

Identical_ro[Identical_ro$Metric=="MSE for MLE" & Identical_ro$Model %in% Selected_Models_mMSE,] %>%
  ggplot(.,aes(x=Subsample_Size,y=log(`Estimated Values`),color=Model,linetype=Model,shape=Model))+
  scale_x_continuous(labels = unique(Identical_ro$Subsample_Size),
                     breaks = unique(Identical_ro$Subsample_Size))+
  geom_point(size=1.25)+geom_line(size=0.75)+
  scale_color_manual(values=Colors_mMSE)+
  scale_linetype_manual(values=LineType_mMSE)+
  scale_shape_manual(values = ShapeType_mMSE)+
  facet_wrap(~Covariate,scales = "free_y",ncol = 2,labeller = label_parsed)+
  xlab(expression(paste(r[0],'+ r = 1000 and ',r[0])))+
  ylab("log(SMSE)")+#expand_limits(y = 0)+
  scale_y_continuous(breaks = scales::pretty_breaks(n = length(unique(Identical_ro$Subsample_Size))/2))+
  theme_bw()+Theme_special()->p7


Identical_ro[Identical_ro$Metric=="MSE for MLE" & Identical_ro$Model %in% Selected_Models_mVc,] %>%
  ggplot(.,aes(x=Subsample_Size,y=log(`Estimated Values`),color=Model,linetype=Model,shape=Model))+
  scale_x_continuous(labels = unique(Identical_ro$Subsample_Size),
                     breaks = unique(Identical_ro$Subsample_Size))+
  geom_point(size=1.25)+geom_line(size=0.75)+
  scale_color_manual(values=Colors_mVc)+
  scale_linetype_manual(values=LineType_mVc)+
  scale_shape_manual(values = ShapeType_mVc)+
  facet_wrap(~Covariate,scales = "free_y",ncol = 2,labeller = label_parsed)+
  xlab(expression(paste(r[0],'+ r = 1000 and ',r[0])))+
  ylab("log(SMSE)")+#expand_limits(y = 0)+
  scale_y_continuous(breaks = scales::pretty_breaks(n = length(unique(Identical_ro$Subsample_Size))/2))+
  theme_bw()+Theme_special()->p8

ggarrange(p1,p3,nrow = 2,ncol = 1,legend.grob = Temp_legend_mMSE,legend = "bottom",labels = "auto")
ggarrange(p2,p4,nrow = 2,ncol = 1,legend.grob = Temp_legend_mVc,legend = "bottom",labels = "auto")
ggarrange(p5,nrow = 1,ncol = 1,legend.grob = Temp_legend_mMSE,legend = "bottom")
ggarrange(p6,nrow = 1,ncol = 1,legend.grob = Temp_legend_mVc,legend = "bottom")
ggarrange(p7,nrow = 1,ncol = 1,legend.grob = Temp_legend_mMSE,legend = "bottom")
ggarrange(p8,nrow = 1,ncol = 1,legend.grob = Temp_legend_mVc,legend = "bottom")

ggarrange(p1,p3,nrow = 2,ncol = 1,legend.grob = Temp_legend_mMSE,legend = "bottom",labels = "auto") %>%
  ggexport(filename = here("Article_Plots","r1_SMSE_MI_PR_TV_Uni_mMSE.pdf"),res=300,width = 12,height = 16)
ggarrange(p2,p4,nrow = 2,ncol = 1,legend.grob = Temp_legend_mVc,legend = "bottom",labels = "auto") %>%
  ggexport(filename = here("Article_Plots","r1_SMSE_MI_PR_TV_Uni_mVc.pdf"),res=300,width = 12,height = 16)
ggarrange(p5,nrow = 1,ncol = 1,legend.grob = Temp_legend_mMSE,legend = "bottom") %>%
  ggexport(filename = here("Article_Plots","r1_ACCURACY_PR_TV_Uni_mMSE.pdf"),res=300,width = 12,height = 12)
ggarrange(p6,nrow = 1,ncol = 1,legend.grob = Temp_legend_mVc,legend = "bottom") %>%
  ggexport(filename = here("Article_Plots","r1_ACCURACY_PR_TV_Uni_mVc.pdf"),res=300,width = 12,height = 12)

ggarrange(p7,nrow = 1,ncol = 1,legend.grob = Temp_legend_mMSE,legend = "bottom") %>%
  ggexport(filename = here("Article_Plots","r1_SMSE_for_MLE_MI_PR_TV_Uni_mMSE.pdf"),res=300,width = 12,height = 12)
ggarrange(p8,nrow = 1,ncol = 1,legend.grob = Temp_legend_mVc,legend = "bottom") %>%
  ggexport(filename = here("Article_Plots","r1_SMSE_for_MLE_MI_PR_TV_Uni_mVc.pdf"),res=300,width = 12,height = 12)

ggarrange(p1,p3,nrow = 2,ncol = 1,legend.grob = Temp_legend_mMSE,legend = "bottom",labels = "auto") %>%
  ggsave(filename = here("Article_Plots","r1_SMSE_MI_PR_TV_Uni_mMSE.eps"),device="eps",dpi=300,width = 12,height = 16)
ggarrange(p2,p4,nrow = 2,ncol = 1,legend.grob = Temp_legend_mVc,legend = "bottom",labels = "auto") %>% 
  ggsave(filename = here("Article_Plots","r1_SMSE_MI_PR_TV_Uni_mVc.eps"),device="eps",dpi=300,width = 12,height = 16)
ggarrange(p5,nrow = 1,ncol = 1,legend.grob = Temp_legend_mMSE,legend = "bottom") %>%
  ggsave(filename = here("Article_Plots","r1_ACCURACY_PR_TV_Uni_mMSE.eps"),device="eps",dpi=300,width = 12,height = 12)
ggarrange(p6,nrow = 1,ncol = 1,legend.grob = Temp_legend_mVc,legend = "bottom") %>%
  ggsave(filename = here("Article_Plots","r1_ACCURACY_PR_TV_Uni_mVc.eps"),device="eps",dpi=300,width = 12,height = 12)

ggarrange(p7,nrow = 1,ncol = 1,legend.grob = Temp_legend_mMSE,legend = "bottom") %>%
  ggexport(filename = here("Article_Plots","r1_SMSE_for_MLE_MI_PR_TV_Uni_mMSE.eps"),res=300,width = 12,height = 12)
ggarrange(p8,nrow = 1,ncol = 1,legend.grob = Temp_legend_mVc,legend = "bottom") %>%
  ggexport(filename = here("Article_Plots","r1_SMSE_for_MLE_MI_PR_TV_Uni_mVc.eps"),res=300,width = 12,height = 12)
```

