---
title: "Best Sub-sampling Method: `r params$Model_Path`"
author: "M.Amalan"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,fig.width = 12,fig.height = 12,message = FALSE,warning = FALSE)
library(here)
library(ggplot2)
library(dplyr)
library(tidyr)
library(LaplacesDemon)
library(xtable)
library(flextable)
library(grid)
library(cowplot)
library(linguisticsdown)
library(ggpubr)
```

```{r load Data}
Old_Labels<-c("Real Model",paste0("Assumed Model ",1:3))
New_Labels<-c("RM",paste0("AM ",1:3))

# Random Sampling
load(here("Non_Identical_r0","Summary","Classical",params$Model_Path,"Data","Efficiency",
          "No_Correlated_Covariate_RS.RData"))

for (i in 1:length(Old_Labels)) 
{
  All_Bias$Model[All_Bias$Model==Old_Labels[i]] <-paste0("RS ",New_Labels[i])
  All_EMSE$Model[All_EMSE$Model==Old_Labels[i]] <-paste0("RS ",New_Labels[i])
  All_Info$Model[All_Info$Model==Old_Labels[i]] <-paste0("RS ",New_Labels[i])
  All_MSE$Model[All_MSE$Model==Old_Labels[i]] <-paste0("RS ",New_Labels[i])
  All_VAR$Model[All_VAR$Model==Old_Labels[i]] <-paste0("RS ",New_Labels[i])
  Accuracy_Data$Model[Accuracy_Data$Model==Old_Labels[i]] <-paste0("RS ",New_Labels[i])
}

RS_Bias<-All_Bias 
RS_EMSE<-All_EMSE
RS_Info<-All_Info
RS_MSE<-All_MSE
RS_VAR<-All_VAR
RS_ACC<-Accuracy_Data

remove(All_Bias,All_EMSE,All_MSE,All_Info,All_VAR,Accuracy_Data)

# OSMAC
load(here("Identical_r0","Summary","Classical",params$Model_Path,"Data","Efficiency",
          "No_Correlated_Covariate_OSMAC.RData"))
remove_stuff<-c(paste0("Assumed New ",1:3))

All_Bias<-All_Bias[!(All_Bias$Model %in% remove_stuff),]
All_EMSE<-All_EMSE[!(All_EMSE$Model %in% remove_stuff),]
All_MSE<-All_MSE[!(All_MSE$Model %in% remove_stuff),]
All_Info<-All_Info[!(All_Info$Model %in% remove_stuff),]
All_VAR<-All_VAR[!(All_VAR$Model %in% remove_stuff),]
Accuracy_Data<-Accuracy_Data[!(Accuracy_Data$Model %in% remove_stuff),]

Old_Labels<-c("Real",paste0("Assumed Old ",1:3),"Model Free")
New_Labels<-c("RM",paste0("AM ",1:3),"MF")


## mMSE
for (i in 1:length(Old_Labels)) 
{
  All_Bias$Model[All_Bias$Model==Old_Labels[i] & All_Bias$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
  All_EMSE$Model[All_EMSE$Model==Old_Labels[i] & All_Bias$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
  All_Info$Model[All_Info$Model==Old_Labels[i] & All_Bias$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
  All_MSE$Model[All_MSE$Model==Old_Labels[i] & All_Bias$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
  All_VAR$Model[All_VAR$Model==Old_Labels[i] & All_Bias$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
  Accuracy_Data$Model[Accuracy_Data$Model==Old_Labels[i] & All_Bias$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
}

OSMAC_mMSE_Bias<-All_Bias[All_Bias$Type == "mMSE",] 
OSMAC_mMSE_EMSE<-All_EMSE[All_EMSE$Type == "mMSE",]
OSMAC_mMSE_Info<-All_Info[All_Info$Type == "mMSE",]
OSMAC_mMSE_MSE<-All_MSE[All_MSE$Type == "mMSE",]
OSMAC_mMSE_VAR<-All_VAR[All_VAR$Type == "mMSE",]
OSMAC_mMSE_ACC<-Accuracy_Data[Accuracy_Data$Type == "mMSE",]

## mVc
for (i in 1:length(Old_Labels)) 
{
  All_Bias$Model[All_Bias$Model==Old_Labels[i] & All_Bias$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
  All_EMSE$Model[All_EMSE$Model==Old_Labels[i] & All_Bias$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
  All_Info$Model[All_Info$Model==Old_Labels[i] & All_Bias$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
  All_MSE$Model[All_MSE$Model==Old_Labels[i] & All_Bias$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
  All_VAR$Model[All_VAR$Model==Old_Labels[i] & All_Bias$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
  Accuracy_Data$Model[Accuracy_Data$Model==Old_Labels[i] & All_Bias$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
}

OSMAC_mVc_Bias<-All_Bias[All_Bias$Type == "mVc",] 
OSMAC_mVc_EMSE<-All_EMSE[All_EMSE$Type == "mVc",]
OSMAC_mVc_Info<-All_Info[All_Info$Type == "mVc",]
OSMAC_mVc_MSE<-All_MSE[All_MSE$Type == "mVc",]
OSMAC_mVc_VAR<-All_VAR[All_VAR$Type == "mVc",]
OSMAC_mVc_ACC<-Accuracy_Data[Accuracy_Data$Type == "mVc",]

remove(All_Bias,All_EMSE,All_MSE,All_Info,All_VAR,Accuracy_Data)

# All elements
All_Bias<-rbind(RS_Bias,
                OSMAC_mMSE_Bias[,!(colnames(OSMAC_mMSE_Bias) %in% "Type")],
                OSMAC_mVc_Bias[,!(colnames(OSMAC_mVc_Bias) %in% "Type")])
All_EMSE<-rbind(RS_EMSE,
                OSMAC_mMSE_EMSE[,!(colnames(OSMAC_mMSE_EMSE) %in% "Type")],
                OSMAC_mVc_EMSE[,!(colnames(OSMAC_mVc_EMSE) %in% "Type")])
All_MSE<-rbind(RS_MSE,
                OSMAC_mMSE_MSE[,!(colnames(OSMAC_mMSE_MSE) %in% "Type")],
                OSMAC_mVc_MSE[,!(colnames(OSMAC_mVc_MSE) %in% "Type")])
All_Info<-rbind(RS_Info,
                OSMAC_mMSE_Info[,!(colnames(OSMAC_mMSE_Info) %in% "Type")],
                OSMAC_mVc_Info[,!(colnames(OSMAC_mVc_Info) %in% "Type")])
All_VAR<-rbind(RS_VAR,
                OSMAC_mMSE_VAR[,!(colnames(OSMAC_mMSE_VAR) %in% "Type")],
                OSMAC_mVc_VAR[,!(colnames(OSMAC_mVc_VAR) %in% "Type")])
All_ACC<-rbind(RS_ACC,
                OSMAC_mMSE_ACC[,!(colnames(OSMAC_mMSE_ACC) %in% "Type")],
                OSMAC_mVc_ACC[,!(colnames(OSMAC_mVc_ACC) %in% "Type")])

All_Objects<-ls()
remove(list = All_Objects[startsWith(All_Objects,"RS")])
```

# Best Sub-sampling Method : `r params$Model_Path`

# Compare SMSE, EMSE, Variance, Information and Bias for all methods.

```{r Compare All}
All_Bias%>%
  ggplot(.,aes(x=Subsample_Size,y=mean_Bias,color=Model))+
  geom_point()+geom_line()+scale_colour_viridis_d()+
  theme_light()+xlab("Sub sample size")+
  ylab("Bias")+ggtitle("Bias")->p1

All_MSE %>%
  ggplot(.,aes(x=Subsample_Size,y=MSE,color=Model))+
  geom_point()+geom_line()+scale_colour_viridis_d()+
  theme_light()+xlab("Sub sample size")+
  ylab("MSE")+ggtitle("MSE")->p2

All_EMSE %>%
  ggplot(.,aes(x=Subsample_Size,y=EMSE,color=Model))+
  geom_point()+geom_line()+scale_colour_viridis_d()+
  theme_light()+xlab("Sub sample size")+
  ylab("EMSE")+ggtitle("EMSE")->p3

All_VAR %>%
  ggplot(.,aes(x=Subsample_Size,y=mean_Variance,color=Model))+
  geom_point()+geom_line()+scale_colour_viridis_d()+
  theme_light()+xlab("Sub sample size")+
  ylab("Variance")+ggtitle("Variance")->p4

All_Info %>%
  ggplot(.,aes(x=Subsample_Size,y=mean_Info,color=Model))+
  geom_point()+geom_line()+scale_colour_viridis_d()+
  theme_light()+xlab("Sub sample size")+
  ylab("Information")+ggtitle("Information")->p5

All_ACC %>%
  ggplot(.,aes(x=Subsample_Size,y=Average_Accuracy,color=Model))+
  geom_point()+geom_line()+scale_colour_viridis_d()+
  theme_light()+xlab("Sub sample size")+
  ylab("Average MSE y")+ggtitle("Average MSE y")->p6

ggarrange(p1,p2,p3,p4,p5,p6,common.legend = TRUE)
```

# Compare  SMSE, EMSE, Variance, Information and Bias for mMSE.
## (Real Model and Assumed Model results with Full Data Real Model)

```{r Compare 1}
OSMAC_mMSE_Bias %>%
  ggplot(.,aes(x=Subsample_Size,y=mean_Bias,color=Model))+
  geom_point()+geom_line()+scale_colour_viridis_d()+
  theme_light()+xlab("Sub sample size")+
  ylab("Bias")+ggtitle("Bias")->p1

OSMAC_mMSE_MSE %>%
  ggplot(.,aes(x=Subsample_Size,y=MSE,color=Model))+
  geom_point()+geom_line()+scale_colour_viridis_d()+
  theme_light()+xlab("Sub sample size")+
  ylab("MSE")+ggtitle("MSE")->p2

OSMAC_mMSE_EMSE %>%
  ggplot(.,aes(x=Subsample_Size,y=EMSE,color=Model))+
  geom_point()+geom_line()+scale_colour_viridis_d()+
  theme_light()+xlab("Sub sample size")+
  ylab("EMSE")+ggtitle("EMSE")->p3

OSMAC_mMSE_VAR %>% 
  ggplot(.,aes(x=Subsample_Size,y=mean_Variance,color=Model))+
  geom_point()+geom_line()+scale_colour_viridis_d()+
  theme_light()+xlab("Sub sample size")+
  ylab("Variance")+ggtitle("Variance")->p4

OSMAC_mMSE_Info %>%
  ggplot(.,aes(x=Subsample_Size,y=mean_Info,color=Model))+
  geom_point()+geom_line()+scale_colour_viridis_d()+
  theme_light()+xlab("Sub sample size")+
  ylab("Information")+ggtitle("Information")->p5

OSMAC_mMSE_ACC %>%
  ggplot(.,aes(x=Subsample_Size,y=Average_Accuracy,color=Model))+
  geom_point()+geom_line()+scale_colour_viridis_d()+
  theme_light()+xlab("Sub sample size")+
  ylab("Average MSE y")+ggtitle("Average MSE y")->p6

ggarrange(p1,p2,p3,p4,p5,p6,common.legend = TRUE)
```

# Compare  SMSE, EMSE, Variance, Information and Bias for mVc.
## (Real Model and Assumed Model results with Full Data Real Model)

```{r Compare 2}
OSMAC_mVc_Bias %>%
  ggplot(.,aes(x=Subsample_Size,y=mean_Bias,color=Model))+
  geom_point()+geom_line()+scale_colour_viridis_d()+
  theme_light()+xlab("Sub sample size")+
  ylab("Bias")+ggtitle("Bias")->p1

OSMAC_mVc_MSE %>%
  ggplot(.,aes(x=Subsample_Size,y=MSE,color=Model))+
  geom_point()+geom_line()+scale_colour_viridis_d()+
  theme_light()+xlab("Sub sample size")+
  ylab("MSE")+ggtitle("MSE")->p2

OSMAC_mVc_EMSE %>%
  ggplot(.,aes(x=Subsample_Size,y=EMSE,color=Model))+
  geom_point()+geom_line()+scale_colour_viridis_d()+
  theme_light()+xlab("Sub sample size")+
  ylab("EMSE")+ggtitle("EMSE")->p3

OSMAC_mVc_VAR %>% 
  ggplot(.,aes(x=Subsample_Size,y=mean_Variance,color=Model))+
  geom_point()+geom_line()+scale_colour_viridis_d()+
  theme_light()+xlab("Sub sample size")+
  ylab("Variance")+ggtitle("Variance")->p4

OSMAC_mVc_Info %>%
  ggplot(.,aes(x=Subsample_Size,y=mean_Info,color=Model))+
  geom_point()+geom_line()+scale_colour_viridis_d()+
  theme_light()+xlab("Sub sample size")+
  ylab("Information")+ggtitle("Information")->p5

OSMAC_mVc_ACC %>%
  ggplot(.,aes(x=Subsample_Size,y=Average_Accuracy,color=Model))+
  geom_point()+geom_line()+scale_colour_viridis_d()+
  theme_light()+xlab("Sub sample size")+
  ylab("Average MSE y")+ggtitle("Average MSE y")->p6

ggarrange(p1,p2,p3,p4,p5,p6,common.legend = TRUE)
```